"""REF-03 exact-rational oracle; independent axis-permutation circulation.

Generate with --write; otherwise compare the committed small golden header.
No production code or solver outputs are loaded. Python standard library only.
"""
from fractions import Fraction as Q
from itertools import permutations, product
from pathlib import Path
import sys

CELLS = (5, 4, 3)
SPACING = tuple(map(Q, (2, 3, 5)))
DT = Q(1, 10**9)
MU = Q('1.25663706127e-6')
EPS = 1 / (MU * 299792458**2)
NAMES = ('Ex', 'Ey', 'Ez', 'Hx', 'Hy', 'Hz')
SHIFTS = ((Q(1, 2), 0, 0), (0, Q(1, 2), 0), (0, 0, Q(1, 2)),
          (0, Q(1, 2), Q(1, 2)), (Q(1, 2), 0, Q(1, 2)), (Q(1, 2), Q(1, 2), 0))


def indices(c):
    return product(*(range(CELLS[a] + (SHIFTS[c][a] == 0)) for a in range(3)))


def point(c, idx):
    return tuple((idx[a] + SHIFTS[c][a]) * SPACING[a] for a in range(3))


def wall(c, idx):
    p = point(c, idx)
    return any(p[a] in (0, CELLS[a] * SPACING[a]) for a in range(3))


def circulation(data, target, idx):
    if target < 3 and wall(target, idx):
        return Q(0)
    p = point(target, idx)
    answer = Q(0)
    # Curl_t = epsilon_tab d_a F_b, from orientation, without six stencil cases.
    for axes in permutations(range(3)):
        t, a, b = axes
        if t != target % 3:
            continue
        inversions = sum(axes[i] > axes[j] for i in range(3) for j in range(i+1, 3))
        sign = (-1)**inversions
        source = b + (3 if target < 3 else 0)
        endpoints = []
        for side in (1, -1):
            location = list(p)
            location[a] += side * SPACING[a] / 2
            raw = tuple(location[d] / SPACING[d] - SHIFTS[source][d] for d in range(3))
            assert all(v.denominator == 1 and v >= 0 for v in raw)
            endpoints.append(data[source, tuple(map(int, raw))])
        answer += sign * (endpoints[0] - endpoints[1]) / SPACING[a]
    return answer


def verify_state(data):
    assert all(v == 0 for (c, idx), v in data.items() if wall(c, idx))
    for electric in (True, False):
        for idx in product(*(range(1 if electric else 0, n) for n in CELLS)):
            div = Q(0)
            for a in range(3):
                hi, lo = list(idx), list(idx)
                if electric:
                    lo[a] -= 1
                else:
                    hi[a] += 1
                c = a + (0 if electric else 3)
                div += (data[c, tuple(hi)] - data[c, tuple(lo)]) / SPACING[a]
            assert div == 0


def generate():
    keys = [(c, idx) for c in range(6) for idx in indices(c)]
    potential = {}
    for c, idx in keys:
        p = point(c, idx)
        inside = all(SPACING[a] <= p[a] <= (CELLS[a]-1)*SPACING[a] for a in range(3))
        potential[c, idx] = Q((17*idx[0]+31*idx[1]+43*idx[2]+13*c) % 101 - 50, 100) if inside else Q(0)
    initial = {(c, idx): circulation(potential, c, idx) for c, idx in keys}
    verify_state(initial)
    states = [initial]
    for family in (range(3, 6), range(3), range(3, 6), range(3)):
        old = states[-1]
        new = old.copy()
        for c, idx in keys:
            if c not in family or (c < 3 and wall(c, idx)):
                continue
            factor = DT / EPS if c < 3 else -DT / MU
            new[c, idx] += factor * circulation(old, c, idx)
        verify_state(new)
        states.append(new)
    lines = [
        '// Generated by scripts/generate_reference_steps.py; exact rational oracle, not solver output.',
        '#pragma once', '#include <array>', '#include <cstddef>',
        'namespace reference_golden {',
        'struct Sample { std::size_t component; std::array<std::size_t, 3> index; std::array<double, 5> stages; };',
        'inline constexpr std::array<Sample, 513> samples{{',
    ]
    for c, idx in keys:
        values = ', '.join(float(s[c, idx]).hex() for s in states)
        lines.append('    {%d, {%s}, {%s}},' % (c, ', '.join(map(str, idx)), values))
    lines.extend(['}};', '} // namespace reference_golden', ''])
    return '\n'.join(lines)


def main():
    output = Path(__file__).resolve().parents[1] / 'tests/reference_steps_golden.hpp'
    expected = generate()
    if sys.argv[1:] == ['--write']:
        output.write_bytes(expected.encode('utf-8'))
        print('WROTE:', output.name)
    elif sys.argv[1:]:
        raise SystemExit('Usage: generate_reference_steps.py [--write]')
    elif output.read_text(encoding='utf-8') != expected:
        raise SystemExit('FAIL: golden header differs from exact-rational calculation')
    print('PASS: 513 samples x 5 stages; exact zero walls and E/H divergence at every stage')
    print('LIMIT: deterministic reference calculations, not physical solver validation')


if __name__ == '__main__':
    main()
